### ISSUE TITLE
@livechat/design-system

### ISSUE THREAD

**Issue by mariosant** [livechat/sample-apps-2#1]
Hi, I think `@livechat/design-system` package you've been using is a private one.

**Comment by mariosant** [comment]
@dominikslawkowski thoughts?

**Comment by dominikslawkowski** [comment]
Hi @mariosant, sure you're right. I will take care that the application can be installed correctly.

**Comment by mariosant** [comment]
Thanks @dominikslawkowski! Does that mean you guys are open sourcing `livechat/design-system`?

**Comment by dominikslawkowski** [comment]
@mariosant yes, but the design system will only be developed by our team from LiveChat.

**Comment by mariosant** [comment]
That's even better, @dominikslawkowski !

**Comment by dominikslawkowski** [comment]
@mariosant, here we go!
https://www.npmjs.com/package/@livechat/design-system

**Comment by mariosant** [comment]
Thanks so much @dominikslawkowski !
